Methods zp vd
learn-academy-2022-bravo/ruby-challenges pull request #20
Opened 2022-04-14 23:55 UTC by VanDexter

2022-04-15 15:48 UTC, elysemontano reviewed
Looks like you have an empty file on this branch called puts, please go ahead and remove it before merging.

2022-04-19 16:18 UTC, elysemontano requested changes
Looks like you have an empty file on this branch called puts, please go ahead and remove it before merging.

2022-04-21 16:49 UTC, VanDexter commented
deleted the file =)

2022-04-21 16:58 UTC, elysemontano approved these changes

2022-04-21 22:58 UTC, merged